---
title: "fonctions-de-debit"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fonctions-de-debit}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---




```r
library(SIVA)
```

<!-- WARNING - This vignette is generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand -->

# Débit d'une vanne : debit_vanne

Deux conditions sont utilisées pour les vannes, (1) le canal (la vanne
est hors d'eau) et (2) l'orifice noyé.

(1) Pour la loi de canal deux conditions sont proposées dans la formule
    du logiciel Infoworks: $h_2/h_1<=0.98$ écoulement libre,
    $h_2/h_1>0.98$ écoulement noyé. En pratique, dans le cas des très
    grandes ouvertures de vanne, les écoulements libres sont assez
    rares. Pour le calcul des coefficients de débits, des paramètres un
    peu arbitraires ont été choisis (10 m de longueur de radier dans la
    formule $C_d$). Dans le cas où l'écoulement est noyé par l'aval la
    formule canal s'écrit (source Infoworks):

$$      
\begin{align*}
C_d=&(1-0.01\frac{10}{l})\left(10(1-\frac{0.01}{2h_1})\right)^{1.5}\\   
Q_{va}=&C_d \mu_{vw}(\frac{2}{3})^{1.5} g^{0.5} l h_1 (\frac{h_1-h_2}{1-0.98})^{0.5}                
\end{align*}
$$

Dans le cas où l'écoulement est libre la formule est plus simple (source
Infoworks):

$$      
\begin{align*}  
Q_{va}=&C_d \mu_{vw}(\frac{2}{3})^{1.5} g^{0.5} l h_1 ^{1.5}                
\end{align*}
$$

Pour l'orifice noyé, deux conditions de noyage de la vanne sont
considérés. Nous avons en pratique calé deux coefficients séparés pour
les conditions où la vanne est fortement noyée ($h_1\geq1.5h_0$) et les
conditions ou elle sort plus de l'eau ($h_1<1.5h_0$) $$
\begin{align*}
C_e=&0.61(1+0.15\frac{l+2h_0}{(2l+2h_0})\\
\end{align*} 
$$ $$
Q=
\begin{cases}
C_e\mu_{vg}h_0l(2g\Delta)^{0.5}~si~h_1<1.5h_0\\
C_e\mu_{vgs}h_0l(2g\Delta)^{0.5}~si~h_1\geq1.5h_0
\end{cases} 
$$

**Fonction de calcul de débit pour une vanne**

Choisir `canal="bazin"` pour avoir les calculs qui étaient fait avant
2018 au barrage. Aubuisson et horton pour calculer les débits suivant
Ferrette (2004) en prenant ou non compte des vitesses Par rapport à
Ferette (2004), la formule en orifice dénoyé calcule les vitesses par
iteration. Le calcul est effectué à partir d'une indexation des
conditions de débits (vecteur de valeurs vrai et faux) entre crochet.
Les coefficients de Bazin ont été recalculés par une 'regression' loess
sur la base du rapport annexé à Briand et Woimant (2015)


```r
# Exploration des coefficients la formule de Bazin 

H=c(5:11)
Rh=c(2,2.25,2.5,2.8,3,3.2,3.4)
K=c(118,125,133,140,146,152,156)
plot(Rh,K)
points(Rh,predict(lm(K~Rh)),type="l")
```

![plot of chunk examples-debit_vanne](figure/examples-debit_vanne-1.png)

```r
gamma=87*Rh/(K+sqrt(Rh))
plot(H,gamma,pch="A")
df<-data.frame(H=H,gamma=gamma)
loess_gamma_bazin<-loess(gamma~H,data=df,control = loess.control(surface = "direct")) # contol pour extrapolation en dehors de la gamme
#save(loess_gamma_bazin,file=str_c(datawd,"loess_gamma_bazin.Rdata"))
df2<-data.frame(H=seq(from=5,to=11,by=0.1)) # pour les prédictions
df2$gamma<-predict(loess_gamma_bazin,newdata=df2)
points(df2$H,df2$gamma,col="red")
```

![plot of chunk examples-debit_vanne](figure/examples-debit_vanne-2.png)

```r

# utilisation de la fonction de débit pour une vanne
# chargement des paramètres et des données de la base
param <- SIVA::param
dat <- SIVA::dat2019
# Calcul du débit d'une vanne
Qva1 <-
  debit_vanne(
    hvilaine = dat$niveauvilaineb,
    hmer = dat$niveaumerb,
    hvanne = dat$vanne1,
    canal = "ifsw",
    Cvg = param["Cvg"],
    Cvgs = param["Cvgs"],
    Cvw = param["Cvw"],
    loi_orificenoye = "ifws"
  )
plot(Qva1[4000:5000,])
```

![plot of chunk examples-debit_vanne](figure/examples-debit_vanne-3.png)

# Débit de l'ensemble des vannes : debit_vannes


```r
# chargement des paramètres
param <- SIVA::param
# les valeurs ajustées des paramètres sont
knitr::kable(param)
```



|     |         x|
|:----|---------:|
|Cvo  | 0.6272291|
|Cvg  | 1.5318200|
|Cvgs | 1.0422057|
|Cvw  | 3.3404224|

```r
dat <- SIVA::dat2019
head(dat)
#>              HoroDate volet1 volet2 volet3 volet4 volet5 vanne1 vanne2 vanne3
#> 1 2019-01-01 00:20:00   1.38   1.38   4.03   1.38   1.38      0      0      0
#> 2 2019-01-01 00:30:00   1.38   1.38   4.03   1.38   1.38      0      0      0
#> 3 2019-01-01 00:40:00   1.38   1.38   4.03   1.38   1.38      0      0      0
#> 4 2019-01-01 00:50:00   1.38   1.38   4.03   1.38   1.38      0      0      0
#> 5 2019-01-01 01:00:00   1.38   1.38   4.03   1.38   1.38      0      0      0
#> 6 2019-01-01 01:10:00   1.38   1.38   4.03   1.38   1.38      0      0      0
#>   vanne4 vanne5 debit_vilaine_estime debit_passe debit_moyen_cran
#> 1      0      0               40.397         2.1           54.926
#> 2      0      0               41.170         2.2           54.390
#> 3      0      0               41.721         2.3           55.761
#> 4      0      0               42.500         2.4           57.532
#> 5      0      0               42.828         2.5           58.785
#> 6      0      0               43.384         2.6           59.375
#>   tot_vol_barrage tot_vol_passe tot_vol_siphon tot_vol_volet tot_vol_ecluse
#> 1               0             0              0         19200              0
#> 2               0             0              0         19200              0
#> 3               0             0              0         19200              0
#> 4               0             0              0         19200              0
#> 5               0             0              0         19232              0
#> 6               0             0              0         19232              0
#>   niveauvilaine niveaumer niveauvilaineb niveaumerb debit_siphon_1
#> 1         1.882     1.285          1.882      1.285          0.892
#> 2         1.888     1.330          1.888      1.330          0.852
#> 3         1.892     1.407          1.892      1.407          0.775
#> 4         1.898     1.454          1.898      1.454          0.725
#> 5         1.900     1.505          1.900      1.505          0.658
#> 6         1.904     1.557          1.904      1.558          0.604
#>   debit_siphon_2 debit_vanne1 debit_vanne2 debit_vanne3 debit_vanne4
#> 1              0            0            0            0            0
#> 2              0            0            0            0            0
#> 3              0            0            0            0            0
#> 4              0            0            0            0            0
#> 5              0            0            0            0            0
#> 6              0            0            0            0            0
#>   debit_vanne5 debit_volet1 debit_volet2 debit_volet3 debit_volet4 debit_volet5
#> 1            0        9.353        9.353            0        9.353        9.353
#> 2            0        9.521        9.521            0        9.521        9.521
#> 3            0        9.634        9.634            0        9.634        9.634
#> 4            0        9.804        9.804            0        9.804        9.804
#> 5            0        9.861        9.861            0        9.861        9.861
#> 6            0        9.975        9.975            0        9.975        9.975
#>   tot_vol day    dm week  diff  lev3 lev25  lev2 lev1.5 diffniveaumer daypb25
#> 1   19200   1 FALSE    1    NA FALSE FALSE FALSE  FALSE         FALSE   FALSE
#> 2   19200   1 FALSE    1 FALSE FALSE FALSE FALSE  FALSE         FALSE   FALSE
#> 3   19200   1 FALSE    1 FALSE FALSE FALSE FALSE  FALSE         FALSE   FALSE
#> 4   19200   1 FALSE    1 FALSE FALSE FALSE FALSE  FALSE         FALSE   FALSE
#> 5   19232   1 FALSE    1 FALSE FALSE FALSE FALSE  FALSE         FALSE   FALSE
#> 6   19232   1 FALSE    1 FALSE FALSE FALSE FALSE  FALSE         FALSE   FALSE
#>   daypb3        p          r resvilinfm03 resvilinfm2 daypbvilinf2
#> 1  FALSE 1.836368 0.04563173        FALSE       FALSE        FALSE
#> 2  FALSE 1.836368 0.05163173        FALSE       FALSE        FALSE
#> 3  FALSE 1.836368 0.05563173        FALSE       FALSE        FALSE
#> 4  FALSE 1.836368 0.06163173        FALSE       FALSE        FALSE
#> 5  FALSE 1.836368 0.06363173        FALSE       FALSE        FALSE
#> 6  FALSE 1.836368 0.06763173        FALSE       FALSE        FALSE
```

# Débit d'un volet : debit_volet

Le fonctionnement en volet est déduit de l'absence d'ouverture de vanne,
de la position du codeur, du niveau Vilaine et du niveau mer. Il semble,
mais ce point reste à confirmer, que la formule par défaut du barrage ne
calcule que pour les positions de codeur au dessus du fin de course
(\>1.38). La hauteur du volet varie en théorie entre 1.38 et 4.03 m NGF.
En pratique il y a des dérives du niveau du codeur qui font qu'on ne
peut utiliser que l'information sur la baisse du volet et une valeur
approximative permettant de sélectionner les positions volet ouvert
(\<3.5m).

$$
\begin{align*}
si~&h_{vilaine}\geq 1.38~\& \\
&h_{volet}<3.5~\&\\
&h_0=0~\&\\
&h_{vilaine}>h_{mer}+0.3\\
&Q_{vo}=l'*\mu_{vo}(\frac{2}{3}g)^{0.5}(h_{vilaine}-1.38)^{1.5}
\end{align*}
$$


```r
param <- SIVA::param
dat <- SIVA::dat2019
dv <-debit_volet(
  hvolet = dat$volet1,
  hvilaine = dat$niveauvilaine,
  hvanne = dat$vanne1,
  hmer = dat$niveaumer,
  Cvo = param["Cvo"]
)
```

# Débit de l'ensemble des volets : debit_volets


```r

dat <- head(SIVA::dat2019,5000)
Qvo12345 <- debit_volets(
  hvolet1 = dat$volet1,
  hvolet2 = dat$volet2,
  hvolet3 = dat$volet3,
  hvolet4 = dat$volet4,
  hvolet5 = dat$volet5,
  hvilaine = dat$niveauvilaine,
  hmer = dat$niveaumer,
  hvanne1 = dat$vanne1,
  hvanne2 = dat$vanne2,
  hvanne3 = dat$vanne3,
  hvanne4 = dat$vanne4,
  hvanne5 = dat$vanne5,
  Cvo = param["Cvo"]
)
print(dat$horodate)
#> NULL
print( rowSums(Qvo12345) * 600)
#>    [1] 22455.65643 22859.44845 23129.97273 23537.74312 23674.19359 23947.88201
#>    [7] 24222.61704 24016.46780 24498.39471 24844.57705 24844.57705 25192.37481
#>   [13] 25262.12755 25331.94455 25541.78052 25611.85397 25611.85397 25822.45787
#>   [19] 25822.45787 25963.17952 26245.38645 26457.70804 26528.60853 26599.57224
#>   [25] 26741.68909 26741.68909 26884.05814 27169.55108 27169.55108 27241.08125
#>   [31] 27241.08125 27527.82801 27527.82801 27671.57628 27527.82801 27671.57628
#>   [37] 27959.82043 27815.57389 27959.82043 28104.31544 28176.65600 28394.04924
#>   [43] 12561.34319 11632.81609 11060.50017 11194.29564 10993.80380 10927.24203
#>   [49] 10662.34649 10695.33981 10563.57064 10301.67148 10171.54607 10041.97321
#>   [55] 10106.69042  9977.39473  9752.46687  9402.48115  9370.87619  9307.77278
#>   [61]  9244.81166  9025.57289  8777.17146  8592.39273  8469.93699  8684.61828
#>   [67]  8623.09811  8746.28407  8653.83997  8653.83997  8531.09162  8592.39273
#>   [73]  8531.09162  8531.09162  8684.61828  8653.83997  8561.72389  8653.83997
#>   [79]  8715.43300  8777.17146  8715.43300  8808.09512  9056.78523  9307.77278
#>   [85] 18995.01718 19377.03279 19633.11487 19633.11487 19633.11487 19954.78946
#>   [91] 19825.91056 19825.91056 10139.10096  9307.77278  9025.57289  8994.39649
#>   [97]  8963.25607  8777.17146  8561.72389  8561.72389  8257.05439  9119.31755
#>  [103] 19633.11487 19761.57556 19825.91056 20473.07970 20213.38085 20343.09214
#>  [109] 19954.78946 20343.09214 20603.34296 20473.07970 20603.34296 20343.09214
#>  [115] 20213.38085 20278.20192 20343.09214 20343.09214 20668.57779 20473.07970
#>  [121] 20213.38085 21127.14128 21258.77433 21788.02342 21788.02342 21987.60759
#>  [127] 22455.65643 22657.25259 22724.58467 22994.57798 23265.63217 23674.19359
#>  [133] 23537.74312 23674.19359 23674.19359 23947.88201 23810.90672 24016.46780
#>  [139] 24016.46780 24222.61704 24291.46386 24636.67331 24705.90984 24705.90984
#>  [145] 25122.68638 25262.12755 25401.82575 25611.85397 25892.78682 26245.38645
#>  [151] 26599.57224 26599.57224 26884.05814 26884.05814 26884.05814 27169.55108
#>  [157] 26884.05814 27241.08125 27384.32952 27456.04752 27527.82801 27527.82801
#>  [163] 27815.57389 27815.57389 27815.57389 27815.57389 28104.31544 28104.31544
#>  [169] 28394.04924 28249.05852 28394.04924 28611.99870 28830.50298 28611.99870
#>  [175] 28684.77189 29122.70264 29122.70264 29342.49605 29342.49605 29342.49605
#>  [181] 29489.33072 29636.40951 29636.40951 29636.40951 29783.73201 30301.27417
#>  [187] 13299.78612 12491.75136 12214.67638 11632.81609 12111.30852 11768.87156
#>  [193] 11768.87156 11429.72423 11194.29564 11194.29564 10662.34649 10662.34649
#>  [199] 10563.57064 10432.34710 10171.54607  9912.95528  9497.50859  9561.03694
#>  [205]  9688.51640  9720.47410  9056.78523  8870.05110  8901.08333  9119.31755
#>  [211]  8901.08333  9088.03346  8963.25607  8746.28407  9056.78523  9244.81166
#>  [217]  8715.43300  8653.83997  9056.78523  8994.39649  8901.08333  8963.25607
#>  [223]  9088.03346  9181.99314  9150.63746  9529.25512  9465.79739 19249.41263
#>  [229]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [235] 20083.94643 20603.34296 20083.94643 20603.34296 20538.17690 10465.10171
#>  [241] 10041.97321 10041.97321  9880.78778  9752.46687  9784.49466  8963.25607
#>  [247]  9497.50859  8777.17146  8684.61828  8561.72389  9025.57289 19761.57556
#>  [253] 21127.14128 20668.57779 20930.20342 20083.94643 20278.20192 19825.91056
#>  [259] 20473.07970 20213.38085 19825.91056 19761.57556 20019.33323 20213.38085
#>  [265] 19825.91056 20213.38085 20083.94643 20473.07970 19633.11487 19122.07389
#>  [271] 20213.38085 20603.34296 20733.88132 20930.20342 21721.63028 21788.02342
#>  [277] 21854.48406 22187.79749 22187.79749 22455.65643 22657.25259 22994.57798
#>  [283] 22994.57798 23129.97273 23129.97273 23742.51736 23537.74312 24016.46780
#>  [289] 23810.90672 23401.55581 24016.46780 24222.61704 24429.35276 24844.57705
#>  [295] 25122.68638 24705.90984 25401.82575 25681.99138 25822.45787 25541.78052
#>  [301] 26316.09694     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [307]     0.00000     0.00000 27887.66607 27671.57628 27887.66607 27887.66607
#>  [313] 27527.82801 27169.55108 27527.82801 27527.82801 28249.05852 27527.82801
#>  [319] 27887.66607 28104.31544 28176.65600 28394.04924 28539.28716 28830.50298
#>  [325] 28830.50298 29122.70264 29342.49605 29342.49605 29489.33072 29122.70264
#>  [331] 29195.90590 29342.49605 29195.90590 29342.49605 29342.49605 13979.91021
#>  [337] 12561.34319 11973.94100 11871.25868 11700.77790 11564.98636 11362.29233
#>  [343] 11328.62630 10993.80380 10662.34649 10399.62674  9945.15761 10894.01171
#>  [349]  9880.78778  9912.95528  9497.50859  9688.51640  9370.87619  9276.27441
#>  [355]  9276.27441  9088.03346  9088.03346  8870.05110  8808.09512  8777.17146
#>  [361]  8623.09811  8653.83997  8531.09162  8500.49597  9056.78523  8684.61828
#>  [367]  8901.08333  8653.83997  8963.25607  8963.25607  9307.77278 20213.38085
#>  [373] 19440.94820 18301.27492 20019.33323 20408.05142     0.00000     0.00000
#>  [379]     0.00000     0.00000     0.00000     0.00000     0.00000 21655.30472
#>  [385] 10794.52340  9880.78778 10041.97321  9720.47410  9816.55743  9624.70632
#>  [391]  9784.49466  9497.50859  9339.30672  9465.79739 10366.94066 21324.69298
#>  [397] 21589.04681 21390.67962 20864.69421 20930.20342 21127.14128 21127.14128
#>  [403] 21854.48406 21522.85660 21522.85660 21390.67962 21127.14128 21854.48406
#>  [409] 21324.69298 21258.77433 21324.69298 21721.63028 21390.67962 21522.85660
#>  [415] 21987.60759 22121.00033 22121.00033 22388.59128 22657.25259 22994.57798
#>  [421] 22994.57798 23401.55581 23401.55581 23401.55581 23742.51736 23810.90672
#>  [427] 23742.51736 23947.88201 24016.46780 23742.51736 24222.61704 24636.67331
#>  [433] 24463.86562 24291.46386 24705.90984 24705.90984 24844.57705 25122.68638
#>  [439] 25401.82575 25541.78052 25681.99138 26033.63588 26245.38645 26316.09694
#>  [445]     0.00000     0.00000     0.00000     0.00000     0.00000 27527.82801
#>  [451]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [457]     0.00000     0.00000 29489.33072 29342.49605 29195.90590 29857.48452
#>  [463] 29342.49605 29342.49605 29415.88285 29636.40951 29931.29781 29931.29781
#>  [469] 29783.73201 30079.10652 30301.27417 30523.98612 30227.15774 30375.45107
#>  [475] 30227.15774 30523.98612 30598.34417 30523.98612 30821.77980 15410.88990
#>  [481] 13513.33948 12911.22893 12700.91288 12180.18790 12249.19736 11632.81609
#>  [487] 11768.87156 11362.29233 11060.50017 10993.80380 10728.36709 10497.89053
#>  [493] 10236.53985  9912.95528  9816.55743  9912.95528  9119.31755  9370.87619
#>  [499]  9307.77278  8439.41471  8561.72389  8870.05110  8715.43300  8439.41471
#>  [505]  8287.35549  8287.35549  8015.98217  8136.22066  8196.56330  7896.34189
#>  [511]  8166.37340  7986.01590  8196.56330  8196.56330  8287.35549  8076.02682
#>  [517] 12888.58910 17184.78547     0.00000     0.00000     0.00000     0.00000
#>  [523]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [529]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [535] 20733.88132 20603.34296 20864.69421 20864.69421 20930.20342 20930.20342
#>  [541] 21192.92374 21324.69298 21589.04681 21854.48406 21788.02342 21987.60759
#>  [547] 22455.65643 22522.78841 22121.00033 22187.79749 22522.78841 22657.25259
#>  [553] 22455.65643 22724.58467 22724.58467 22657.25259 22994.57798 22724.58467
#>  [559] 22724.58467 22724.58467 22994.57798 22926.98003 22994.57798 23129.97273
#>  [565] 23333.56100 23401.55581 23537.74312 23537.74312 23401.55581 23674.19359
#>  [571] 23674.19359 23674.19359 24085.11895 24153.83538 24016.46780 24222.61704
#>  [577] 24153.83538 24429.35276 24705.90984 24844.57705 24705.90984 24636.67331
#>  [583] 24705.90984 24360.37579 24983.50272 25122.68638 24983.50272 25401.82575
#>  [589] 25401.82575     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [595]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [601]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [607]     0.00000     0.00000 29783.73201 29489.33072 29931.29781 29783.73201
#>  [613] 29931.29781 30227.15774 30079.10652 30079.10652 30227.15774 30896.37869
#>  [619] 14818.20475 14124.52926 13835.78814 13656.33704 13406.42106 13335.29955
#>  [625] 13052.07793 12911.22893 12911.22893 12631.06377 12422.28852 12042.55947
#>  [631] 12111.30852 11905.45336 11531.12112 11261.39420 11227.82821 10927.24203
#>  [637] 10794.52340 10761.42830 10236.53985 10009.66661  9816.55743  9561.03694
#>  [643]  9465.79739  9276.27441  9088.03346  8901.08333  8684.61828  8777.17146
#>  [649]  8653.83997  8561.72389  8287.35549  8257.05439  8136.22066  8136.22066
#>  [655]  7986.01590  8045.98583  7896.34189  7956.08707  7896.34189 17307.67995
#>  [661] 17307.67995 17307.67995 17307.67995 17184.78547     0.00000     0.00000
#>  [667]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [673]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [679]     0.00000     0.00000     0.00000     0.00000     0.00000 21788.02342
#>  [685] 21788.02342 21721.63028 21987.60759 22054.27035 22455.65643 22254.66174
#>  [691] 22388.59128 22657.25259 22657.25259 22994.57798 22859.44845 22724.58467
#>  [697] 22859.44845 22859.44845 22994.57798 23265.63217 23265.63217 22791.98331
#>  [703] 23129.97273 23129.97273 23265.63217 23401.55581 23537.74312 23265.63217
#>  [709] 23537.74312 23674.19359 23674.19359 23674.19359 24016.46780 23810.90672
#>  [715] 23947.88201 23742.51736 24016.46780 23947.88201 24291.46386 24291.46386
#>  [721] 24291.46386 24636.67331 24636.67331 24705.90984 24844.57705 24983.50272
#>  [727] 24983.50272 25401.82575 25262.12755 25122.68638 25262.12755 25401.82575
#>  [733] 25611.85397 25541.78052 25611.85397 26033.63588     0.00000     0.00000
#>  [739]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [745]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [751]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [757] 30005.17183 30079.10652 30079.10652 30079.10652 30227.15774 30598.34417
#>  [763] 14928.74226 14597.95295 14561.35132 14378.80333 14305.99935 14305.99935
#>  [769] 14052.15772 13979.91021 13763.91401 13584.77554 13370.84454 13264.30426
#>  [775] 13122.69323 12911.22893 12665.97228 12596.18740 12318.33666 12145.73193
#>  [781] 11973.94100 11973.94100 11564.98636 11328.62630 11127.33087 10927.24203
#>  [787] 10761.42830 10596.46187 10366.94066 10301.67148 10106.69042 10009.66661
#>  [793]  9816.55743  9752.46687  9497.50859  9402.48115  9276.27441  9276.27441
#>  [799]  8963.25607  9088.03346  9088.03346  9088.03346  8870.05110  8777.17146
#>  [805]  8901.08333 19058.51024 19122.07389 19249.41263 19249.41263 19249.41263
#>  [811] 19122.07389 19313.18757     0.00000     0.00000     0.00000     0.00000
#>  [817]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [823]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [829]     0.00000     0.00000     0.00000 23333.56100 23537.74312 23537.74312
#>  [835] 23265.63217 23537.74312 23947.88201 23810.90672 23810.90672 23742.51736
#>  [841] 24016.46780 24016.46780 24291.46386 24291.46386 24085.11895 23810.90672
#>  [847] 24222.61704 24291.46386 24429.35276 24636.67331 24705.90984 24705.90984
#>  [853] 24291.46386 24567.50158 24705.90984 24705.90984 24705.90984 24705.90984
#>  [859] 24844.57705 25122.68638 25122.68638 24844.57705 25262.12755 25262.12755
#>  [865] 25262.12755 25122.68638 25401.82575 25401.82575 25611.85397 25611.85397
#>  [871] 25892.78682 26316.09694 26245.38645 26245.38645 26245.38645 26528.60853
#>  [877] 26741.68909 26884.05814 26741.68909 26599.57224 26670.59911 26741.68909
#>  [883] 26884.05814 27169.55108     0.00000     0.00000     0.00000     0.00000
#>  [889]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [895]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [901]     0.00000     0.00000     0.00000     0.00000     0.00000 31045.75667
#>  [907] 30896.37869 31045.75667 30821.77980 31045.75667 30821.77980 30896.37869
#>  [913] 31195.37461 15299.17208 14965.64891 14744.66536 14561.35132 14415.25149
#>  [919] 14233.31866 13979.91021 13979.91021 13763.91401 13763.91401 13513.33948
#>  [925] 13299.78612 13264.30426 12981.58976 12770.89026 12422.28852 12318.33666
#>  [931] 12111.30852 12042.55947 11905.45336 11395.99165 11362.29233 11227.82821
#>  [937] 10927.24203 10794.52340 10465.10171 10301.67148 10301.67148 10106.69042
#>  [943]  9977.39473  9720.47410  9688.51640  9624.70632  9592.85402  9402.48115
#>  [949]  9434.12157  9561.03694  9307.77278  9402.48115  9276.27441  9307.77278
#>  [955]  9434.12157  9434.12157  9497.50859  9848.65515     0.00000     0.00000
#>  [961]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [967]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [973]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#>  [979] 23265.63217 23265.63217 23401.55581 23674.19359 23742.51736 23947.88201
#>  [985] 24222.61704 24429.35276 24291.46386 24429.35276 24429.35276 24429.35276
#>  [991] 24705.90984 24705.90984 24844.57705 24705.90984 24705.90984 24705.90984
#>  [997] 24705.90984 24705.90984 24705.90984 24983.50272 25122.68638 24983.50272
#> [1003] 24983.50272 24983.50272 24983.50272 25192.37481 25192.37481 25262.12755
#> [1009] 25122.68638 25401.82575 25401.82575 25401.82575 25541.78052 25822.45787
#> [1015] 25822.45787 25822.45787 25892.78682 26033.63588 26033.63588 25892.78682
#> [1021] 26316.09694 26599.57224 26741.68909 26812.84212 26741.68909 26955.33711
#> [1027] 26884.05814 27169.55108 27169.55108 27169.55108 27241.08125     0.00000
#> [1033]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1039]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1045]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1051]     0.00000     0.00000 31195.37461 30747.24106 30598.34417 30821.77980
#> [1057] 15747.66443 15261.99306 14965.64891 14928.74226 14891.86600 14671.24802
#> [1063] 14305.99935 14451.73040     0.00000     0.00000     0.00000     0.00000
#> [1069]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1075]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1081]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1087]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1093]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1099]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1105]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1111]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1117]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1123]     0.00000     0.00000     0.00000 12214.67638 12283.75079 18425.62619
#> [1129] 18425.62619 18425.62619 18633.43279 18842.01479 18842.01479 18842.01479
#> [1135] 18946.59566 18946.59566 19051.36932 18998.95841 18998.95841 19156.33539
#> [1141] 18842.01479 19156.33539 18998.95841 18789.79675 18998.95841 19156.33539
#> [1147] 18894.28110 18998.95841 19366.84340 19366.84340 19156.33539 19261.49354
#> [1153] 19472.38464 19314.14452 19525.22691 19578.11690 19525.22691 19949.67918
#> [1159] 19843.28103 19737.07271 19737.07271 19949.67918 19949.67918 20216.50283
#> [1165] 20216.50283 20163.04361 20216.50283 20430.81094 20323.56272 20216.50283
#> [1171] 20216.50283 20377.16331 20377.16331 20538.24714 20592.03564 20753.68221
#> [1177] 20645.87101 20753.68221 20969.86532     0.00000     0.00000     0.00000
#> [1183]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1189]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1195]     0.00000     0.00000     0.00000     0.00000     0.00000 15898.11919
#> [1201]     0.00000     0.00000  7686.81026  7649.58604  7686.81026  7630.99653
#> [1207]  7519.77663  7482.82445  7409.10238  7372.33268  7335.62401  7280.67566
#> [1213]  7152.99968  7026.07886  6953.89347  6917.89407  6810.27031  6738.83428
#> [1219]  6649.89306  6490.79488  6455.61447  6280.67160  6176.47746  6055.65426
#> [1225]  5935.62934  5918.54840  5630.69710  5664.31315  5613.91411  5364.18355
#> [1231]  5281.78532  5364.18355  5085.77303  5004.83331  4908.27872     0.00000
#> [1237]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1243]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1249]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1255]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1261]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1267]     0.00000     0.00000     0.00000     0.00000 23129.97273 23401.55581
#> [1273] 23265.63217 23742.51736 23674.19359 23605.93549 23947.88201 24016.46780
#> [1279] 23982.16673 23947.88201 24429.35276 24291.46386 24016.46780 24291.46386
#> [1285] 24016.46780 24844.57705 25122.68638 25262.12755 25262.12755 24983.50272
#> [1291] 25611.85397 25331.94455 25331.94455 25331.94455 25192.37481 25331.94455
#> [1297] 25331.94455 25262.12755 25331.94455 25611.85397 25262.12755 25822.45787
#> [1303] 25401.82575 25541.78052 25892.78682 25752.19270 25822.45787 26033.63588
#> [1309] 25892.78682 26033.63588 26245.38645 26245.38645 26599.57224 26599.57224
#> [1315] 26599.57224 26884.05814 26741.68909 26599.57224 26884.05814 26955.33711
#> [1321] 27169.55108 26955.33711 27599.67095 27527.82801 27527.82801 27671.57628
#> [1327] 27959.82043     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1333]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1339]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1345]     0.00000     0.00000 30896.37869 30523.98612 30449.68841 30523.98612
#> [1351]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1357]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1363]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1369]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1375]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1381]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1387]     0.00000     0.00000     0.00000 11429.72423 11429.72423 11328.62630
#> [1393] 11227.82821 11328.62630 11194.29564 11194.29564 11194.29564 11194.29564
#> [1399] 11328.62630 11328.62630 11700.77790 23265.63217 23537.74312     0.00000
#> [1405]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1411]     0.00000     0.00000     0.00000     0.00000 24636.67331 24775.21111
#> [1417] 25122.68638 25262.12755 24844.57705 25262.12755 25262.12755 25541.78052
#> [1423] 25262.12755 25611.85397 25611.85397 25471.77110 25541.78052 25822.45787
#> [1429] 25541.78052 25401.82575 25681.99138 25892.78682 25822.45787 25822.45787
#> [1435] 25822.45787 25822.45787 25892.78682 25822.45787 25822.45787 26033.63588
#> [1441] 26033.63588 25963.17952 25822.45787 25611.85397 25822.45787 26245.38645
#> [1447] 26033.63588 26316.09694 25963.17952 25963.17952 26457.70804 26316.09694
#> [1453] 26457.70804 26316.09694 26457.70804 26457.70804 26457.70804 26599.57224
#> [1459] 26316.09694 26599.57224 26955.33711 26884.05814 26884.05814 26955.33711
#> [1465] 26955.33711 26955.33711 27026.67896 27169.55108 27241.08125 27527.82801
#> [1471] 27527.82801 27241.08125 27527.82801 27456.04752 27527.82801     0.00000
#> [1477]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1483]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1489]     0.00000     0.00000     0.00000     0.00000 30079.10652     0.00000
#> [1495]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1501]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1507]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1513]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1519]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1525]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1531]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1537]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1543]     0.00000     0.00000 17500.17075 17704.45162 17653.30734 17960.91151
#> [1549] 17653.30734 17704.45162 17806.88802 17960.91151 18012.35085 18166.96278
#> [1555] 18012.35085 18373.79604     0.00000     0.00000 18633.43279     0.00000
#> [1561] 18842.01479 18737.62704 18685.50570 18894.28110 18894.28110 18998.95841
#> [1567] 19208.89048 19366.84340 19366.84340 19366.84340 19419.59012 19631.05455
#> [1573] 19737.07271 19419.59012 19631.05455 19631.05455 19631.05455 19949.67918
#> [1579] 19631.05455 19843.28103 19737.07271 19949.67918 19949.67918 19737.07271
#> [1585] 19843.28103 19737.07271 19949.67918 19949.67918 19843.28103 20056.26682
#> [1591] 19737.07271 19843.28103 19737.07271 19843.28103 20056.26682 20056.26682
#> [1597] 20109.63159 20109.63159 20056.26682 20216.50283 20216.50283 20216.50283
#> [1603] 20216.50283 20430.81094 20216.50283 20430.81094 20430.81094 20430.81094
#> [1609] 20538.24714 20645.87101 20645.87101 20645.87101 20753.68221 20645.87101
#> [1615] 20753.68221 20861.68042 20861.68042 21078.23658 21132.49200 21132.49200
#> [1621] 21132.49200 21132.49200 21349.97799 21349.97799 21513.57891     0.00000
#> [1627]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1633]     0.00000     0.00000 22337.79900 22559.32989     0.00000     0.00000
#> [1639] 22725.95563 21622.87724 22837.26631 22725.95563 22781.58831 22614.82638
#> [1645]  7649.58604  7724.09467  7445.93300  7409.10238  7409.10238  7335.62401
#> [1651]  7207.62575  7189.40167  7171.19297  7152.99968  7098.51231  7044.16400
#> [1657]  6953.89347  6864.01188  6792.38777  6738.83428  6579.02424  6473.19671
#> [1663]  6385.44513  6402.96349  6332.98614  6176.47746  6124.59868  6072.86597
#> [1669]  6055.65426  6004.11695  5901.48387  5884.43578  5765.56056  5681.14617
#> [1675]  5714.86211  5714.86211  5681.14617  5580.39826  5546.94937  5513.56759
#> [1681]  5463.62101     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1687]     0.00000     0.00000     0.00000     0.00000     0.00000 11093.89874
#> [1693] 11227.82821 11328.62630 11294.99357 11093.89874 11294.99357 11463.49002
#> [1699] 11227.82821     0.00000     0.00000     0.00000 11632.81609 11632.81609
#> [1705] 11802.96775 11871.25868 12008.23390 12076.91769 12145.73193 12214.67638
#> [1711] 12214.67638 12457.00380 12561.34319 12457.00380 12561.34319 12770.89026
#> [1717] 12665.97228 12770.89026 12805.92698 12876.09635 12946.39341 13016.81794
#> [1723] 13016.81794 13016.81794 13016.81794 13228.85402 13158.04847 13158.04847
#> [1729] 13158.04847 13228.85402 13158.04847 13228.85402 13264.30426 13370.84454
#> [1735] 13370.84454 13406.42106 13477.66855 13620.54063 13620.54063 13620.54063
#> [1741] 13549.04182 13692.16476 13763.91401 13692.16476 13871.77197 13835.78814
#> [1747] 13835.78814 13871.77197 13835.78814 13871.77197 13871.77197 13979.91021
#> [1753] 14052.15772 14088.32800 14160.76148 14305.99935 14160.76148 14197.02462
#> [1759] 14088.32800 14305.99935 14305.99935 14415.25149 14451.73040 14524.78034
#> [1765] 14561.35132 14707.94142 14818.20475 14818.20475 14891.86600 14891.86600
#> [1771] 14891.86600 15150.63708 15002.58591 15224.84420 15410.88990     0.00000
#> [1777]     0.00000     0.00000     0.00000 15560.26783 15672.61607 15560.26783
#> [1783] 15560.26783 15672.61607 15785.23340 15785.23340 15860.46080 15898.11919
#> [1789] 15747.66443 15860.46080 15860.46080 15785.23340 15747.66443     0.00000
#> [1795]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1801]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1807]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1813]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1819]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1825]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1831]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1837]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1843]     0.00000 12946.39341 18998.95841 19103.82832 19366.84340 19208.89048
#> [1849] 19525.22691 19156.33539 19103.82832 19103.82832 18998.95841 18998.95841
#> [1855] 19208.89048 19103.82832 19366.84340 19419.59012 19366.84340 19843.28103
#> [1861] 19631.05455 19631.05455 19843.28103 19843.28103 19737.07271 19419.59012
#> [1867] 19896.45640 19843.28103 20056.26682 20109.63159 20323.56272 20056.26682
#> [1873] 20109.63159 20163.04361 20109.63159 20109.63159 20109.63159 20056.26682
#> [1879] 20056.26682 20109.63159 20430.81094 20538.24714 20538.24714 20430.81094
#> [1885] 20538.24714 20323.56272 20645.87101 20538.24714 20538.24714 20538.24714
#> [1891] 20323.56272 20323.56272 20592.03564 20645.87101 20807.65796 20807.65796
#> [1897] 20915.74955 20969.86532 21078.23658 21078.23658 21078.23658 20969.86532
#> [1903] 20969.86532 20969.86532 21078.23658 20969.86532 21078.23658 21132.49200
#> [1909] 21241.14221 20969.86532 21078.23658 21132.49200 21132.49200 21241.14221
#> [1915] 21078.23658 21295.53693 21349.97799 21241.14221 21349.97799 21349.97799
#> [1921] 21568.20500 21677.59559 21787.17051 21896.92942 21842.02698 21896.92942
#> [1927] 21787.17051 21842.02698 21842.02698 21896.92942 22006.87204 21896.92942
#> [1933] 21842.02698 22006.87204 21951.87779 21896.92942 21842.02698 21842.02698
#> [1939] 21896.92942 22061.91213     0.00000     0.00000     0.00000     0.00000
#> [1945]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1951]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1957]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1963]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1969]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [1975]     0.00000     0.00000     0.00000     0.00000     0.00000 19896.45640
#> [1981] 20109.63159 19896.45640 19843.28103 20216.50283 19896.45640 19896.45640
#> [1987] 20109.63159 19896.45640 20002.94933 19896.45640 19896.45640 20216.50283
#> [1993] 19843.28103 20002.94933 19896.45640 19843.28103 19896.45640 20056.26682
#> [1999] 20216.50283 20216.50283 20216.50283 20538.24714 20645.87101 20645.87101
#> [2005] 20645.87101 20753.68221 20753.68221 21078.23658 20753.68221 20753.68221
#> [2011] 20807.65796 21078.23658 20861.68042 20861.68042 21078.23658 20807.65796
#> [2017] 20861.68042 20915.74955 21078.23658 21078.23658 21132.49200 20969.86532
#> [2023] 21241.14221 21132.49200 21241.14221 21132.49200 21295.53693 21241.14221
#> [2029] 21241.14221 21349.97799 21349.97799 21241.14221 21458.99903 21404.46537
#> [2035] 21458.99903 21458.99903 21458.99903 21241.14221 21458.99903 21458.99903
#> [2041] 21349.97799 21458.99903 21677.59559 21568.20500 21458.99903 21568.20500
#> [2047] 21677.59559 21677.59559 21677.59559 21677.59559 21787.17051 21787.17051
#> [2053] 21842.02698 21787.17051 21842.02698 21787.17051 21677.59559 21842.02698
#> [2059] 22061.91213 22061.91213 22061.91213 22006.87204 22061.91213 22061.91213
#> [2065] 22227.30713 22337.79900 22337.79900 22337.79900 22393.11339 22559.32989
#> [2071] 22503.87887 22559.32989 22614.82638 22614.82638 22559.32989 22614.82638
#> [2077] 22503.87887 22614.82638 22725.95563 22725.95563 22614.82638 22559.32989
#> [2083] 15299.17208 15410.88990 15410.88990 15410.88990     0.00000     0.00000
#> [2089]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2095]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2101]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2107]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2113]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2119]     0.00000     0.00000     0.00000     0.00000     0.00000 21349.97799
#> [2125] 21241.14221 21349.97799 20969.86532 21132.49200 20969.86532 21078.23658
#> [2131] 21349.97799 21078.23658 21241.14221 21132.49200 21349.97799 21241.14221
#> [2137] 21458.99903 21677.59559 21568.20500 21568.20500 21568.20500 21951.87779
#> [2143] 21842.02698 21677.59559 21787.17051 22006.87204 21896.92942 22006.87204
#> [2149] 22061.91213 22061.91213 22227.30713 22061.91213 22227.30713 22337.79900
#> [2155] 22061.91213 22227.30713 22227.30713 22006.87204 22393.11339 22061.91213
#> [2161] 22172.12972 22337.79900 22227.30713 22227.30713 22227.30713 22393.11339
#> [2167] 22393.11339 22365.45050 22337.79900 22393.11339 22393.11339 22337.79900
#> [2173] 22559.32989 22503.87887 22393.11339 22559.32989 22559.32989 22393.11339
#> [2179] 22393.11339 22393.11339 22503.87887 22227.30713 22337.79900 22559.32989
#> [2185] 22393.11339 22503.87887 22503.87887 22614.82638 22614.82638 22337.79900
#> [2191] 22559.32989 22559.32989 22503.87887 22614.82638 22614.82638 22559.32989
#> [2197] 22614.82638 22503.87887 22448.47336 22614.82638 22614.82638 22614.82638
#> [2203] 22559.32989     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2209]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2215]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2221]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2227]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2233]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2239]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2245]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2251]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2257]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2263]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2269] 17857.65121 17857.65121 18053.81619 18171.85761 18171.85761 18171.85761
#> [2275] 18211.26171 18171.85761 18329.64454 18211.26171 18211.26171 18093.13483
#> [2281] 18211.26171 18171.85761 18211.26171 18369.16227 18211.26171 18171.85761
#> [2287] 18250.69424 18329.64454 18408.70836 18448.28279 18686.32332 18765.89596
#> [2293] 18686.32332 18845.58123 18845.58123 18845.58123 18965.31996 18845.58123
#> [2299] 18965.31996 18925.37896 18965.31996 19085.31122 19125.36433 19205.55447
#> [2305] 19245.69146 19245.69146 19245.69146 19245.69146 19366.26989 19487.09909
#> [2311] 19729.50771 19851.08612 19851.08612 19851.08612 20013.57745 19932.27659
#> [2317] 19851.08612 19932.27659 19932.27659 19851.08612 19891.66755 19932.27659
#> [2323] 19891.66755 19770.00618 19932.27659 19932.27659 19770.00618 19851.08612
#> [2329] 19891.66755 20054.26923 19932.27659 19851.08612 19932.27659 20013.57745
#> [2335] 20013.57745 19932.27659 19972.91323 19851.08612 19932.27659 20013.57745
#> [2341] 19851.08612 19851.08612 19689.03694 19891.66755 19770.00618 19851.08612
#> [2347]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2353]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2359]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2365]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2371]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2377]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2383]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2389]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2395]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2401]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2407]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2413] 28627.96683 28268.37184 28268.37184 27910.29521 28388.06845 28089.14333
#> [2419] 27910.29521 27910.29521 27850.76385 27910.29521 27910.29521 27850.76385
#> [2425] 27672.42418 28029.48498 27850.76385 28268.37184 28268.37184 27672.42418
#> [2431] 28148.84394 28388.06845 28208.58679 28268.37184 28089.14333 28268.37184
#> [2437] 28447.97994 28148.84394 28447.97994 28268.37184 28388.06845 28148.84394
#> [2443] 28268.37184 28268.37184 28388.06845 28388.06845 28388.06845 28507.93352
#> [2449] 28388.06845 28627.96683 28688.04649 28627.96683 28507.93352 28748.16813
#> [2455] 28989.07379 29049.40483 28989.07379 29049.40483     0.00000     0.00000
#> [2461]     0.00000     0.00000     0.00000     0.00000 29533.55541 29412.26780
#> [2467] 29291.14668 29230.64863 29049.40483 29230.64863 29049.40483 29230.64863
#> [2473] 28868.53719 28989.07379 29230.64863 28989.07379 29049.40483 29230.64863
#> [2479] 28868.53719 29049.40483 29049.40483 29230.64863 29049.40483 29049.40483
#> [2485] 28868.53719 28507.93352 28328.19907 28268.37184 28507.93352     0.00000
#> [2491]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2497]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2503]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2509]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2515]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2521]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2527]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2533]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2539]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2545]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2551]     0.00000     0.00000     0.00000     0.00000     0.00000 28208.58679
#> [2557] 28148.84394 28268.37184 28029.48498 28148.84394 28089.14333 27731.82830
#> [2563] 28029.48498 27969.86894 27672.42418 27850.76385 27494.46681 27672.42418
#> [2569] 27376.04136 27553.74341 27494.46681 27672.42418 27257.78642 27376.04136
#> [2575] 27910.29521 26669.07818 27494.46681 26904.04720 27494.46681 27850.76385
#> [2581] 27910.29521 27731.82830 27494.46681 27613.06254 27672.42418 27613.06254
#> [2587] 27613.06254 27672.42418 27613.06254 27553.74341 27494.46681 27672.42418
#> [2593] 27613.06254 27613.06254 27850.76385 28089.14333 28089.14333 28148.84394
#> [2599]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2605]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2611]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2617]     0.00000     0.00000     0.00000     0.00000 30448.49643 30571.19008
#> [2623] 30387.21131 30387.21131 30387.21131 30448.49643 30387.21131 30387.21131
#> [2629] 30142.48283 30264.76461 30020.36618 30020.36618 29837.50132 29776.62918
#> [2635]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2641]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2647]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2653]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2659]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2665]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2671]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2677]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2683]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2689]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2695]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2701]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2707]  9125.34712 36659.28908 36817.41672 36501.38848 36343.71523 36029.05212
#> [2713] 35793.65406 35872.06293 35872.06293 35793.65406 35793.65406 35558.77091
#> [2719] 35402.46876 35324.40380 34934.94179 34857.22225 35012.71901 34624.41012
#> [2725] 34314.80403 34314.80403 35012.71901 34934.94179 34857.22225 34857.22225
#> [2731] 35012.71901 35012.71901 35402.46876 35324.40380 35402.46876 35168.44631
#> [2737] 35012.71901 35324.40380 35324.40380 35090.55386 35012.71901 35324.40380
#> [2743] 35090.55386 35246.39630 35558.77091     0.00000     0.00000     0.00000
#> [2749]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2755]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2761]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2767]     0.00000     0.00000     0.00000     0.00000 39297.18774 38732.53978
#> [2773] 38652.09838 38330.89084 38010.57803 38250.72866 38010.57803 38170.62244
#> [2779] 19608.17853     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2785]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2791]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2797]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2803]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2809]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2815]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2821]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2827]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2833]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2839]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2845]     0.00000 36029.05212 35558.77091 35715.30241 35558.77091 35168.44631
#> [2851] 35012.71901 35090.55386 35012.71901 35090.55386 35012.71901 34624.41012
#> [2857] 34779.56043 35090.55386 34857.22225 34546.92171 34083.20854 34314.80403
#> [2863] 34314.80403 34546.92171 33929.10224 33468.18255 33544.85649 33468.18255
#> [2869] 33468.18255 33775.22891 33929.10224 33929.10224 33929.10224 34083.20854
#> [2875] 33621.58889 33775.22891 33621.58889 33621.58889 33775.22891 33775.22891
#> [2881] 33775.22891 33929.10224 33852.13643 34083.20854 33929.10224 34237.54745
#> [2887] 34237.54745 34546.92171 34624.41012 34314.80403 34083.20854 34237.54745
#> [2893] 34546.92171 34624.41012     0.00000     0.00000     0.00000     0.00000
#> [2899]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2905]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2911]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2917]     0.00000     0.00000     0.00000     0.00000 38652.09838 19770.00618
#> [2923]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2929]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2935]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2941]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2947]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2953]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2959]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2965]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2971]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2977]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2983]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2989]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [2995] 36264.96397 36107.63237 35793.65406 35558.77091 35793.65406 35872.06293
#> [3001] 35793.65406 35793.65406 35793.65406 35558.77091 35558.77091 35168.44631
#> [3007] 35402.46876 35090.55386 35168.44631 35168.44631 34857.22225 35168.44631
#> [3013] 34624.41012 34701.95637 34546.92171 34546.92171 34546.92171 34546.92171
#> [3019] 34314.80403 34237.54745 34314.80403 34083.20854 33929.10224 33698.37971
#> [3025] 33544.85649 33544.85649 33621.58889 33621.58889 33929.10224 34083.20854
#> [3031] 33929.10224 33929.10224 33852.13643 33929.10224 33621.58889 33775.22891
#> [3037] 33621.58889 33775.22891 33544.85649 33621.58889     0.00000     0.00000
#> [3043]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3049]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3055]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3061]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3067]     0.00000     0.00000     0.00000 38732.53978 29776.62918     0.00000
#> [3073]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3079]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3085]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3091]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3097]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3103]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3109]     0.00000     0.00000     0.00000     0.00000     0.00000 15522.87833
#> [3115] 30747.24106     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3121]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3127]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3133]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3139]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3145] 37691.16245 36896.56558 36343.71523 36422.52341 36501.38848 36422.52341
#> [3151] 36422.52341 36659.28908 36817.41672 36343.71523 36659.28908 36659.28908
#> [3157] 36659.28908 36343.71523 36343.71523 36186.26967 36264.96397 36186.26967
#> [3163] 36343.71523 36186.26967 36029.05212 35872.06293 36343.71523 35715.30241
#> [3169] 35558.77091 35715.30241 35793.65406 35872.06293 35715.30241 35558.77091
#> [3175] 35558.77091 35558.77091 35715.30241 35715.30241 35872.06293 36029.05212
#> [3181] 35872.06293 36029.05212 36107.63237 36343.71523 36029.05212 36186.26967
#> [3187] 36343.71523 36343.71523 36422.52341     0.00000     0.00000     0.00000
#> [3193]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3199]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3205]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3211]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3217]     0.00000     0.00000     0.00000 42492.47321 41995.48838 41912.84723
#> [3223]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3229]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3235]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3241]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3247]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3253]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3259]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3265]  7501.29296 30375.45107     0.00000     0.00000     0.00000     0.00000
#> [3271]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3277]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3283]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3289]     0.00000     0.00000     0.00000 36817.41672 36659.28908 36659.28908
#> [3295] 36422.52341 36343.71523 36343.71523 36422.52341 36422.52341 36343.71523
#> [3301] 36501.38848 36343.71523 36107.63237 36029.05212 36029.05212 36343.71523
#> [3307] 36029.05212 36343.71523 36422.52341 36107.63237 36264.96397 36186.26967
#> [3313] 35558.77091 35872.06293 35872.06293 36029.05212 36029.05212 36186.26967
#> [3319] 35715.30241 35872.06293 35715.30241 35715.30241 36186.26967 36186.26967
#> [3325] 36501.38848 36422.52341 36422.52341 36659.28908 36422.52341 36422.52341
#> [3331] 36817.41672 36896.56558 36817.41672 37531.79192 37134.35179 37213.72695
#> [3337] 37213.72695 37691.16245     0.00000     0.00000     0.00000     0.00000
#> [3343]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3349]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3355]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3361]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3367] 45175.72798 22799.95575     0.00000     0.00000     0.00000     0.00000
#> [3373]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3379]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3385]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3391]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3397]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3403]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3409]  7026.07886 28321.52295 28176.65600 28176.65600 28176.65600     0.00000
#> [3415]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3421]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3427]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3433]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3439]     0.00000     0.00000 35402.46876 34857.22225 34857.22225 34624.41012
#> [3445] 34857.22225 34857.22225 34857.22225 34857.22225 34624.41012 34624.41012
#> [3451] 34624.41012 34624.41012 34624.41012 34624.41012 34314.80403 34314.80403
#> [3457] 34237.54745 34237.54745 34237.54745 34237.54745 34237.54745 33852.13643
#> [3463] 34083.20854 33852.13643 33852.13643 33775.22891 33775.22891 33775.22891
#> [3469] 33775.22891 33775.22891 33775.22891 33929.10224 33929.10224 33929.10224
#> [3475] 34083.20854 34237.54745 34237.54745 34469.49120 34314.80403 34237.54745
#> [3481] 34392.11863 34546.92171 34314.80403 34237.54745 34546.92171 34857.22225
#> [3487]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3493]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3499]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3505]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3511]     0.00000     0.00000     0.00000     0.00000     0.00000 40597.99524
#> [3517]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3523]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3529]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3535]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3541]     0.00000     0.00000     0.00000     0.00000 15410.88990 15560.26783
#> [3547] 15410.88990 21241.14221 20430.81094 19896.45640 19419.59012 19790.15312
#> [3553] 19419.59012 19419.59012 19156.33539 18998.95841 19525.22691 20002.94933
#> [3559] 20753.68221 20969.86532 20915.74955 20430.81094 20216.50283     0.00000
#> [3565]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3571]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3577]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3583]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3589] 33162.07232 33162.07232 33009.36914 32856.90108 32856.90108 33085.69136
#> [3595] 32780.75532 32856.90108 33009.36914 32780.75532 32856.90108 32856.90108
#> [3601] 32856.90108 32856.90108 32856.90108 32856.90108 32780.75532 32856.90108
#> [3607] 33315.01024 33162.07232 33315.01024 33009.36914 32856.90108 32780.75532
#> [3613] 32856.90108 32856.90108 32780.75532 32249.38719 32552.67172 32552.67172
#> [3619] 32476.76190 32552.67172 32476.76190 32476.76190 32476.76190 32476.76190
#> [3625] 32476.76190 32476.76190 32476.76190 32476.76190 32476.76190 32552.67172
#> [3631] 32856.90108 32780.75532 32856.90108 33009.36914 33009.36914 33621.58889
#> [3637]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3643]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3649]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3655]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3661]     0.00000     0.00000 37850.75793 37372.64665  9482.65998     0.00000
#> [3667]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3673]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3679]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3685]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3691]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3697]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3703]     0.00000     0.00000     0.00000     0.00000     0.00000 18894.28110
#> [3709] 19103.82832 18998.95841     0.00000     0.00000     0.00000     0.00000
#> [3715]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3721]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3727]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3733]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3739]     0.00000     0.00000 23340.40175 23677.85010 23790.69120 23677.85010
#> [3745] 23621.49664 23677.85010 23677.85010 23565.18796 23340.40175 23284.31750
#> [3751] 23677.85010 23452.70509 23565.18796 23847.17878 23340.40175 23847.17878
#> [3757] 23677.85010 23903.71100 24073.57511 24016.90920 23847.17878 23790.69120
#> [3763] 23677.85010 24016.90920 23452.70509 23903.71100 23116.33485 23677.85010
#> [3769] 23565.18796 23677.85010 23452.70509 23847.17878 24414.50379 24414.50379
#> [3775] 24585.56649 24642.67581 24757.02686 24757.02686 25043.67534 25216.19167
#> [3781] 25389.10232 25101.13691 25562.40640 25678.16059 25331.42168     0.00000
#> [3787]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3793]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3799]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3805]     0.00000 28989.07379     0.00000     0.00000     0.00000     0.00000
#> [3811]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3817]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3823]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3829]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3835]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3841]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3847]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3853]     0.00000     0.00000 10662.34649 15796.07027 21127.14128 20930.20342
#> [3859] 20668.57779 21721.63028 21127.14128 21061.42703 21987.60759 21788.02342
#> [3865]     0.00000     0.00000 21788.02342 22589.98715 22859.44845 23062.24223
#> [3871] 23537.74312 23537.74312     0.00000     0.00000     0.00000     0.00000
#> [3877]     0.00000     0.00000 26033.63588 26033.63588 26104.15586 25892.78682
#> [3883] 26033.63588 25892.78682 26316.09694 26528.60853 26528.60853 26528.60853
#> [3889] 26741.68909 26955.33711 26955.33711 26955.33711 26955.33711 27241.08125
#> [3895] 27384.32952 27671.57628 27456.04752 27743.54395 27743.54395 27959.82043
#> [3901] 27959.82043 28104.31544 28466.63732 28176.65600 28321.52295 28757.60666
#> [3907] 28466.63732 28466.63732 28466.63732 28466.63732 28757.60666 28684.77189
#> [3913] 28611.99870 28757.60666 28757.60666 28757.60666 28466.63732 28757.60666
#> [3919] 28903.46079 28757.60666 29049.56067 29049.56067 29049.56067 29342.49605
#> [3925] 29636.40951 29562.83963 29636.40951 29710.04032 29857.48452 30005.17183
#> [3931] 30079.10652 30153.10184 30153.10184 30079.10652 30005.17183 30153.10184
#> [3937] 30449.68841 30449.68841 30747.24106 30598.34417 30747.24106 31045.75667
#> [3943] 31045.75667 31120.53567 31045.75667 31345.23213     0.00000     0.00000
#> [3949]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3955]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3961]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3967]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3973]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3979]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3985]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3991]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [3997]     0.00000 24844.57705 25471.77110 25331.94455 25611.85397 25122.68638
#> [4003] 25471.77110 24844.57705 25192.37481 25822.45787 25122.68638 25331.94455
#> [4009] 25611.85397 25611.85397 25822.45787 26174.73941 26316.09694 26599.57224
#> [4015] 26174.73941 26316.09694 26955.33711 27671.57628 27815.57389 27959.82043
#> [4021] 28249.05852 28757.60666 29342.49605     0.00000     0.00000 30153.10184
#> [4027] 29857.48452 29857.48452 30153.10184 30079.10652 30153.10184 30153.10184
#> [4033] 30598.34417 30747.24106 30747.24106 30747.24106 31345.23213 31045.75667
#> [4039] 31045.75667 31120.53567 31420.25062 31570.46680 31570.46680 31720.92161
#> [4045] 32022.54559 31871.61466 32022.54559 31871.61466 32173.71402 32022.54559
#> [4051] 32022.54559 31871.61466 32173.71402 32173.71402 32249.38719 32325.11958
#> [4057] 32325.11958 32476.76190 32325.11958 32173.71402 32476.76190 32325.11958
#> [4063] 32476.76190 32552.67172 32552.67172 32552.67172 32476.76190 32552.67172
#> [4069] 32628.64060 32552.67172 32552.67172 32780.75532 33009.36914 32780.75532
#> [4075] 32780.75532 32780.75532 33085.69136 33162.07232 33009.36914 33162.07232
#> [4081] 33315.01024 33468.18255 33315.01024 33621.58889 34083.20854 33775.22891
#> [4087] 33621.58889 34083.20854 33775.22891 33775.22891 33929.10224 33852.13643
#> [4093] 34083.20854 34237.54745 34546.92171 34392.11863 34392.11863 33852.13643
#> [4099] 34237.54745 34546.92171     0.00000     0.00000     0.00000 35715.30241
#> [4105] 35402.46876 35324.40380     0.00000     0.00000     0.00000     0.00000
#> [4111]     0.00000     0.00000     0.00000 36501.38848 36817.41672 18329.64454
#> [4117] 17936.03146 17584.22315 17506.35951 17196.05931 17041.60427 16887.61445
#> [4123] 17003.06315 16390.37766 16734.09128 16124.69359 16011.27280 15672.61607
#> [4129] 15410.88990 15039.55326 14671.24802 14524.78034 14052.15772 13692.16476
#> [4135] 13692.16476 13228.85402 12735.88555 12770.89026 12318.33666 11227.82821
#> [4141] 10236.53985  9912.95528 12283.75079 25471.77110 25611.85397 26033.63588
#> [4147] 26033.63588 26033.63588 25611.85397 25892.78682 26033.63588 26033.63588
#> [4153] 25611.85397 25122.68638 24914.00761 25331.94455 25541.78052 25541.78052
#> [4159] 25611.85397 26033.63588 25611.85397 25331.94455 26316.09694 26457.70804
#> [4165] 27241.08125 27599.67095 27671.57628 27959.82043 27959.82043 28104.31544
#> [4171] 28611.99870 28611.99870 28611.99870 28684.77189 28466.63732 28684.77189
#> [4177] 28757.60666 29049.56067 29783.73201 29783.73201 29857.48452 29857.48452
#> [4183] 30449.68841 30747.24106 30971.03766 31120.53567 31345.23213 31345.23213
#> [4189] 31570.46680 31720.92161 31720.92161 32173.71402 32325.11958 32476.76190
#> [4195] 32476.76190 32856.90108 33238.51196 33621.58889 33775.22891 33621.58889
#> [4201] 33621.58889 33929.10224 34083.20854 34314.80403 34083.20854 34392.11863
#> [4207] 34546.92171 35012.71901 34857.22225 35090.55386 35324.40380 35402.46876
#> [4213] 35168.44631 35715.30241 36107.63237 36186.26967 36264.96397 36540.84232
#> [4219] 18408.70836 17428.61113 17157.40201 17428.61113 17584.22315 17662.20190
#> [4225] 17312.20506 17662.20190 17273.46086 17312.20506 17273.46086 17506.35951
#> [4231] 17662.20190 17584.22315 17118.77373 16887.61445 16695.78356 16504.68457
#> [4237] 16581.03616 16581.03616 16428.45054 16238.38095 16238.38095 16276.33586
#> [4243] 16542.84568 16657.50512 16542.84568 16542.84568 16276.33586 16162.55979
#> [4249] 16238.38095 16086.85701 16276.33586 16162.55979 16086.85701 16428.45054
#> [4255] 16772.42825     0.00000 17041.60427 16964.55112 16926.06822 17273.46086
#> [4261] 17350.97819 17428.61113 17428.61113 17273.46086 17157.40201 16581.03616
#> [4267] 16542.84568 16619.25598 16734.09128 16504.68457 16200.45558 16086.85701
#> [4273] 15935.80733 15935.80733 15785.23340 15560.26783 15224.84420 14928.74226
#> [4279] 14524.78034 13763.91401 13228.85402 12946.39341 12770.89026 12249.19736
#> [4285] 11939.68081 11531.12112 10894.01171 10695.33981 10041.97321 10465.10171
#> [4291]  9181.99314  8839.05502  8684.61828  8106.10512  7658.86802  7511.67899
#> [4297]  7220.17272  7047.12397  6847.01038  6564.48799  6285.96201  6369.09677
#> [4303]  6258.33143  6148.21576  6011.49063  5929.94887  5794.87360  5821.80559
#> [4309]  5929.94887  5929.94887  5902.85089  5929.94887  6038.75360  7511.67899
#> [4315] 15733.05128 16332.74681 16696.13714 16817.85837     0.00000     0.00000
#> [4321]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4327]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4333]     0.00000     0.00000     0.00000     0.00000 31570.46680 32022.54559
#> [4339] 32780.75532 33085.69136 34083.20854 34469.49120 35090.55386 35090.55386
#> [4345]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4351]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4357]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4363]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4369]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4375]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4381]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4387]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4393]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4399]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4405]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4411]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4417]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4423]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4429]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4435]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4441]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4447]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4453]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4459]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4465]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4471]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4477]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4483]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4489]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4495]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4501]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4507]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4513]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4519]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4525]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4531]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4537]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4543]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4549]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4555]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4561]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4567]  6685.42227  6738.83428  6899.91774  7098.51231  7335.62401  6211.14426
#> [4573]  5782.49318  5714.86211  5513.56759  5496.90190  5232.55086  5216.17355
#> [4579]  4940.39389  4653.88639  4544.01673  4143.67775  3978.04353  3785.22016
#> [4585]  3451.99474  3226.29741  2951.42544  2763.92780  2528.96729  2276.19376
#> [4591]  1949.34051  1741.01271  1518.93479  1390.61841  1038.70350   844.58372
#> [4597]   809.14959   765.57483   568.00209   476.83463   419.07832   311.31101
#> [4603]   317.72967   220.47136   198.06185   181.78810   150.67075   140.73848
#> [4609]   131.03460  2494.34868  3871.12674  4402.60250     0.00000     0.00000
#> [4615]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4621]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4627]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4633]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4639]     0.00000 23112.02914 23664.49348 24381.16717 24943.48683 25591.34963
#> [4645] 26162.75428 27651.25042 28574.31057 28912.46591 29678.14670  6038.45884
#> [4651]  4388.58573  3799.93909  3653.61022  3380.91870  3324.41383  2992.13440
#> [4657]  3019.37680  2750.69273  2580.57788  2464.94472  2239.04872  2020.50888
#> [4663]  1832.63351  1595.51095  1369.60173  1135.74110   944.59868   680.87573
#> [4669]   844.58372   583.70667   363.86285   317.72967   198.06185   121.56459
#> [4675]    82.01477   181.78810   363.86285   405.03175   330.69724   363.86285
#> [4681]   337.24559   357.14549   357.14549   405.03175   454.88537   680.87573
#> [4687]   817.96061   935.35306  1067.51090     0.00000     0.00000     0.00000
#> [4693]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4699]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4705]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4711]  4234.96849  4512.78644  4940.39389  5020.98661  9307.77278  8839.05502
#> [4717]  8653.83997  8561.72389  8777.17146  8592.39273  8653.83997  8317.69357
#> [4723]  8257.05439  8196.56330  7956.08707  7836.74701  7599.87818  7453.07048
#> [4729]  7278.16590  7075.86817  6818.57991  6536.45462  6369.09677  5929.94887
#> [4735]  5554.36807  5317.28505  5032.23807  4853.58935  4602.14012  4233.42744
#> [4741]  3993.38328  3804.73946  3619.16337  3301.94356  3081.37089  2951.48795
#> [4747]  2802.33337  2593.77852  2430.84936  2390.67054  2370.66500  2310.98569
#> [4753]  2271.48220  2330.82241  2271.48220  2251.81576  2310.98569  2718.26692
#> [4759]  9220.97923 10102.54438 10102.54438 10523.03351     0.00000     0.00000
#> [4765]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4771]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4777]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4783]     0.00000     0.00000     0.00000     0.00000 28153.48551 28574.31057
#> [4789] 29422.17890 30020.58475 30536.69095 31142.50951 32278.07233 32895.12118
#> [4795]  6508.40897  5748.64449  5430.40757  5496.90190  5298.23093  5281.78532
#> [4801]  5118.26993  5265.35676  4908.27872  4748.75430  4638.13721  4357.71650
#> [4807]  4250.24799  4083.18670  3829.43401  3610.08636  3366.76274  3198.44458
#> [4813]  2897.43680  2910.90280  2750.69273  2593.53474  2326.03633  2177.59485
#> [4819]  2032.45275  2153.17336  2276.19376  2202.10797  2080.46222  1961.14276
#> [4825]  1879.02794  1832.63351  1798.09230  1752.37947  1729.67063  1718.35329
#> [4831]  1752.37947  1752.37947  1798.09230  1809.58169  1925.80739  2226.71238
#> [4837]  2477.70542  2593.53474  2645.57796  2870.56732     0.00000     0.00000
#> [4843]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4849]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4855]     0.00000     0.00000     0.00000     0.00000  5986.97050  6141.87540
#> [4861]  5850.38895  5816.40804  5833.39025  5833.39025  5901.48387  5799.44235
#> [4867]  5765.56056  5782.49318  5647.49679  5630.69710  5613.91411  5613.91411
#> [4873]  5664.31315  5546.94937  5380.71415  5447.00585  5496.90190  5118.26993
#> [4879]  4924.32758  4796.42701  4622.40583  4435.02555  4326.91999  4143.67775
#> [4885]  3963.09786  3859.00485  3741.17780  3639.08295  3537.93408  3395.09445
#> [4891]  3254.23063  3046.70137  2992.13440  2870.56732  2830.41989  2763.92780
#> [4897]  2724.28619  2737.47884  2711.11479  2645.57796  2632.53486  2567.64267
#> [4903]  2516.11904  2477.70542  2490.48807  2516.11904  2567.64267  9058.13039
#> [4909] 15714.90503     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4915]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4921]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4927]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4933]     0.00000     0.00000     0.00000     0.00000 31927.22565 32014.81746
#> [4939] 32542.04485 12214.67638 11905.45336 11531.12112 11531.12112 11734.80827
#> [4945] 11531.12112 11294.99357 11227.82821 11027.13517 10794.52340 10695.33981
#> [4951] 10530.71352 10236.53985  9912.95528  9497.50859  9088.03346  8653.83997
#> [4957]  8257.05439  8226.79032  7866.52564  7482.35560  7220.17272  7047.12397
#> [4963]  6480.50798  6258.33143  5848.77918  5634.15871  5448.57238  5343.45705
#> [4969]  5213.02643  5032.23807  4627.08393  4552.38752  4602.14012  4627.08393
#> [4975]  4602.14012  4453.42476  4552.38752  4453.42476  4355.18969  4677.10619
#> [4981]  4627.08393  5395.92939  5687.56284  6148.21576     0.00000     0.00000
#> [4987]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4993]     0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
#> [4999]     0.00000     0.00000
plot(
  dat$horodate,
  rowSums(Qvo12345) * 600,
  pch = 19,
  cex = 0.5,
  ylab = "volume 10 min"
)
#> Error in xy.coords(x, y, xlabel, ylabel, log): les longueurs de 'x' et 'y' diffèrent
points(
  dat$horodate,
  dat$tot_vol_volet,
  pch = 19,
  cex = 0.2,
  col = "red"
)
#> Error in xy.coords(x, y): les longueurs de 'x' et 'y' diffèrent


datt <- dat
datt$volvoletcalcule <- rowSums(Qvo12345) * 600
datt$date = as.Date(datt$horodate)
#> Error in `$<-.data.frame`(`*tmp*`, date, value = structure(numeric(0), class = "Date")): le tableau de remplacement a 0 lignes, le tableau remplacé en a 5000
debj <-
  as.data.frame(
    dplyr::select(datt, date, tot_vol_volet, volvoletcalcule) %>%
      dplyr::group_by(date) %>%
      dplyr::summarize(
        volumevoletcalcule = sum(volvoletcalcule),
        volumevoletbarrage = sum(tot_vol_volet)
      ) %>%
      dplyr::mutate(
        debitvoletcalcule = volumevoletcalcule / (24 * 60 * 60),
        debitvoletbarrage = volumevoletbarrage / (24 * 60 * 60)
      )
  )
#> Error in `dplyr::select()`:
#> ! Can't subset columns that don't exist.
#> x Column `date` doesn't exist.

plot(
  debj$date,
  debj$debitvoletcalcule,
  type = "l",
  col = "black",
  ylab = "Debit (m3/s)",
  xlab = "Date",
  ylim = c(0, max(
    c(debj$debitvoletcalcule, debj$debitvoletbarrage), na.rm = TRUE
  ))
)
#> Error in plot(debj$date, debj$debitvoletcalcule, type = "l", col = "black", : objet 'debj' introuvable
points(debj$date,
       debj$debitvoletbarrage,
       type = "l",
       col = "red")
#> Error in points(debj$date, debj$debitvoletbarrage, type = "l", col = "red"): objet 'debj' introuvable
legend(
  "top",
  legend = c("calcul", "barrage"),
  col = c("black", "red"),
  lty = c(1, 1)
)
#> Error in (function (s, units = "user", cex = NULL, font = NULL, vfont = NULL, : plot.new has not been called yet
```

# Débit de l'ensemble du barrage : debit_total

Les données de SIVA étant enregistrées au pas de temps de dix minutes,
le débit instantanné au barrage $Q_{ba}$ s'écrit : $$
Q_{ba}(t)=\frac{\sum_{i=1}^5 \beta Q_{va}(t,i)+\sum_{i=1}^5 \beta
Q_{vo}(t,i)+V_{s}+V_{p}}{\beta}
$$ Avec :\\ $V_s$= volume siphon\\ $V_p$=volume passe \\ $\beta$=600\\
Les écoulements passe $V_p$ et siphon $V_s$, qui sont faible, ne sont
pas recalculés et viennent directement de SIVA. Les Volumes écluse ne
sont pas inclus dans la formule. <!-- TODO voir avec Aldo.-->


```r
param <- SIVA::param
dat <- SIVA::dat2019
Q12345 <- debit_total(param, param0 = param, dat2019)
Q12345$tot_vol <- dat$tot_vol # volume total au barrage d'Arzal
Q12345$volet_vanne <-
  dat$tot_vol_barrage + dat$tot_vol_volet # volume total toutes les dix minutes sur volets et vannes
mQ <-
  reshape2::melt(
    Q12345[, c("horodate",
               "qvanne1",
               "qvanne2",
               "qvanne3",
               "qvanne4",
               "qvanne5")],
    id.vars = "horodate",
    value.name = "Qvanne",
    variable.name = "vanne"
  )
mcond <-
  reshape2::melt(Q12345[, c("horodate",
                  "typecalc1",
                  "typecalc2",
                  "typecalc3",
                  "typecalc4",
                  "typecalc5")], value.name = "typecalc", id.vars = "horodate")
mQ$vanne <- as.character(mQ$vanne)
mQ$vanne <- gsub("qvanne", "", mQ$vanne)
mQ12345 <- cbind(mQ, "typecalc" = mcond[, 3]) # melted object


g <-ggplot2::ggplot(mQ12345, ggplot2::aes(
  x = horodate,
  y = Qvanne,
  col = typecalc,
  shape = vanne
)) + ggplot2::geom_jitter(size = 0.6)

print(g)
```

![plot of chunk example-debit_total](figure/example-debit_total-1.png)

```r

# Calcul du débit journalier
Qj <-
  as.data.frame(
    dplyr::select(
      Q12345,
      Q,
      date,
      volvoletcalcule,
      debit_moyen_cran,
      tot_vol,
      volet_vanne,
      tot_vol_siphon,
      tot_vol_passe
    ) %>%
      dplyr::group_by(date) %>%
      dplyr::summarize(
        volumevilainecalcule = sum(Q * 600, volvoletcalcule, tot_vol_passe, tot_vol_siphon, na.rm =TRUE),
        tot_vol = sum(tot_vol, na.rm = TRUE),
        volet_vanne = sum(volet_vanne),
        debit_moyen_cran = mean(debit_moyen_cran)
      ) %>%
      dplyr::mutate(
        debitvilainecalcule = volumevilainecalcule / (24 * 60 * 60),
        tot_bar = tot_vol / (24 * 60 * 60),
        tot_volvan_bar = volet_vanne / (24 * 60 * 60)
      )
  )
```

# Extraction des données à l'aide des fonctions SIVA : bilansiva-debit

Utilisation de bilansiva pour extraire les débits du barrage. Le tableau
dans cette forme peut être utilisé directement dans les fonctions de
débit.


```r
# Ne pas oublier que la bdd du barrage est en vieux GMT tout pourri.
Sys.setenv(TZ='GMT')	

# mise en place des paramètres de connexion --------------------
 # sur mon ordi j'ai des mots de passe chargés au démarrage à partir de Rprofile.site
 # Ici test si existent et si oui il faut le main password pour les decrypter, sinon il
 # faut les entrer après un prompt du programme. 
 if (interactive()){
 if (!exists("mainpass")) mainpass <- getPass::getPass(msg = "main password")
 if (!exists("hostmysql")) {
   hostmysql. <- getPass::getPass(msg = "Saisir host")
   # ci dessous pour ne pas redemander au prochain tour
   hostmysql <- encrypt_string(string = hostmysql., key = mainpass)
 } else {
   hostmysql. <- decrypt_string(string = hostmysql, key = mainpass)
 }
 if (!exists("pwdmysql")) {
   pwdmysql. <- getPass::getPass(msg = "Saisir password")
   pwdmysql <- encrypt_string(string = pwdmysql., key = mainpass)
 }  else {
   # pass should be loaded
   pwdmysql. <- decrypt_string(string = pwdmysql, key = mainpass)
 }
 if (!exists("umysql")) {
   umysql. <- getPass::getPass(msg = "Saisir user")
   umysql <- encrypt_string(string = umysql., key = mainpass)
 } else {
   umysql. <- decrypt_string(string = umysql, key = mainpass)
 }
 
 pool <- pool::dbPool(
     drv = RMariaDB::MariaDB(),
     dbname = "archive_IAV",
     host = hostmysql.,
     username = umysql.,
     password = pwdmysql.,
     port=3306
 )
 dat <- load_debit_barrage(debut="2020-01-01 00:00:00",
     fin="2020-01-20 00:00:00",
     con=pool)
 knitr::kable(dat)
 rawdata2020 <- dat
 save(rawdata2020, file="../inst/rawdata2020.Rdata")
 }
#> Error in load_debit_barrage(debut = "2020-01-01 00:00:00", fin = "2020-01-20 00:00:00", : La date de debut doit etre au format POSIXct
```

# Traitement des données en sortie de bilansiva-debit : traitement_siva

Le débit du barrage est stocké dans des totaliseurs, le traitement SIVA

-   Transforme les cumuls en différences

-   vire les cumuls négatifs lors de la remise à jour des totaliseurs

-   vire les valeurs trop grandes apparaissant lors des différence sur
    plantage de la base

-   filtre les débits erronés des siphons \> 3.8 $m^3s^{-1}$


```r
# voir example-bilansiva-debit pour le chargement des données de 2020 dans SIVA
load(system.file("rawdata2020.Rdata", package="SIVA"))
plot(rawdata2020$tot_vol_barrage)
```

![plot of chunk example-traitement_siva](figure/example-traitement_siva-1.png)

```r
# les totaliseurs sont remis à plat
cordata2020 <- traitement_siva(dat=rawdata2020)
plot(cordata2020$tot_vol_barrage)
```

![plot of chunk example-traitement_siva](figure/example-traitement_siva-2.png)
