# WARNING - Generated by {fusen} from /dev/flat_databasetools.Rmd: do not edit by hand

test_that("Tablesiva fonctionne", {
  tablesiva <-
    new(
      "Tablesiva",
      debut = as.POSIXct(as.Date("2021-10-25")),
      fin =  as.POSIXct(as.Date("2021-12-01")),
      table = "b_barrage_volet4_hauteur",
      nom = "volet4"
    )
  expect_s4_class(tablesiva,  class="Tablesiva") 
})
