# WARNING - Generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand

test_that("debit_volets works", {
  load(system.file("param2012_2014.Rdata", package = "SIVA"))
load(system.file("dat2019.Rdata", package = "SIVA"))
Qvo12345<-debit_volets(hvolet1=dat$volet1,
		hvolet2=dat$volet2,
		hvolet3=dat$volet3,
		hvolet4=dat$volet4,
		hvolet5=dat$volet5,
		hvilaine=dat$niveauvilaine,
		hmer=dat$niveaumer,
		hvanne1=dat$vanne1,
		hvanne2=dat$vanne2,
		hvanne3=dat$vanne3,
		hvanne4=dat$vanne4,
		hvanne5=dat$vanne5,
		Cvo=param["Cvo"])
expect_is(Qvo12345,"data.frame")
})
