# WARNING - Generated by {fusen} from /dev/flat_databasetools.Rmd: do not edit by hand

test_that("loaddb-method fonctionne et retourne un tableau de données", {
  # attention il faut avoir définit mainpass <- "xxxxx"
  options(stacomiR.dbname="archive_IAV", # TODO not used....
          stacomiR.host = hostmysql.,
          stacomiR.password = pwdmysql.,
          stacomiR.user = umysql.,
          stacomiR.ODBClink = "archive_IAV")
  
  tablesiva <-
    new(
      "Tablesiva",
      debut = as.POSIXct(as.Date("2021-10-25")),
      fin =  as.POSIXct(as.Date("2021-12-01")),
      table = "b_barrage_volet4_hauteur",
      nom = "volet4"
    )
  res <- loaddb(tablesiva)
  expect_s4_class(res,  class="Tablesiva")
  expect_is(res@rawdata,"data.frame")
})
