# WARNING - Generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand

test_that("debit_volet works", {
  load(system.file("param2012_2014.Rdata", package = "SIVA"))
load(system.file("dat2019.Rdata", package = "SIVA"))
dv <-debit_volet(
  hvolet = dat$volet1,
  hvilaine = dat$niveauvilaine,
  hvanne = dat$vanne1,
  hmer = dat$niveaumer,
  Cvo = param["Cvo"]
)
  expect_lt(max(dv), 30)
  expect_gt(max(dv), 0)
})
