# WARNING - Generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand

#' bilansiva-debit extraction des données de la base
#' 
#' Extraction des données des volets, des vannes, le débit vilaine estimé, débit 
#' passe (brut), le débit moyen CRAN, le volume total du barrage, de la passe,
#' des siphons, des volets, de l'écluse, les niveaux vilaine et mer des sondes
#' de la passe, et les niveaux mer et vilaine des sondes barrage.
#' @param debut La date de début, format texte, format = "%Y-%m-%d %H:%M:%S".
#' @param fin La date de fin, format texte, format = "%Y-%m-%d %H:%M:%S".
#' @param plot Boolean défaut FALSE.
#' @return Un tableau de données avec les données chargées
#' 
#' @export
#' @examples
#' # Ne pas oublier que la bdd du barrage est en vieux GMT tout pourri.
#' Sys.setenv(TZ='GMT')	
#' 
#' # mise en place des paramètres de connexion --------------------
#'  # sur mon ordi j'ai des mots de passe chargés au démarrage à partir de Rprofile.site
#'  # Ici test si existent et si oui il faut le main password pour les decrypter, sinon il
#'  # faut les entrer après un prompt du programme. 
#'  if (interactive()){
#'  if (!exists("mainpass")) mainpass <- getPass::getPass(msg = "main password")
#'  if (!exists("hostmysql")) {
#'    hostmysql. <- getPass::getPass(msg = "Saisir host")
#'    # ci dessous pour ne pas redemander au prochain tour
#'    hostmysql <- encrypt_string(string = hostmysql., key = mainpass)
#'  } else {
#'    hostmysql. <- decrypt_string(string = hostmysql, key = mainpass)
#'  }
#'  if (!exists("pwdmysql")) {
#'    pwdmysql. <- getPass::getPass(msg = "Saisir password")
#'    pwdmysql <- encrypt_string(string = pwdmysql., key = mainpass)
#'  }  else {
#'    # pass should be loaded
#'    pwdmysql. <- decrypt_string(string = pwdmysql, key = mainpass)
#'  }
#'  if (!exists("umysql")) {
#'    umysql. <- getPass::getPass(msg = "Saisir user")
#'    umysql <- encrypt_string(string = umysql., key = mainpass)
#'  } else {
#'    umysql. <- decrypt_string(string = umysql, key = mainpass)
#'  }
#'  
#'  options(stacomiR.dbname="archive_IAV", # TODO not used....
#'          stacomiR.host = hostmysql.,
#'          stacomiR.password = pwdmysql.,
#'          stacomiR.user = umysql.,
#'          stacomiR.ODBClink = "archive_IAV")
#'  dat <- bilansiva_debit(debut="2020-01-01 00:00:00",fin="2020-01-20 00:00:00", plot =FALSE)
#'  knitr::kable(dat)
#'  rawdata2020 <- dat
#'  save(rawdata2020, file="inst/rawdata2020.Rdata")
#'  }
bilansiva_debit <- function(debut, fin, plot=FALSE) {
  bil <- new(
    "bilansiva",
    tables = c(
      "b_barrage_volet1_hauteur",
      "b_barrage_volet2_hauteur",
      "b_barrage_volet3_hauteur",
      "b_barrage_volet4_hauteur",
      "b_barrage_volet5_hauteur",
      "b_barrage_vanne1_hauteur",
      "b_barrage_vanne2_hauteur",
      "b_barrage_vanne3_hauteur",
      "b_barrage_vanne4_hauteur",
      "b_barrage_vanne5_hauteur",
      "b_barrage_debit",
      # Débit Vilaine estimé
      "b_barrage_debit",
      "b_pont_de_cran_debit",
      "b_barrage_volume",
      "b_barrage_volume",
      "b_barrage_volume",
      "b_barrage_volume",
      "b_barrage_volume",
      "b_passeapoisson_niveauvilaine",
      "b_passeapoisson_niveaumer",
      "b_barrage_niveau",
      "b_barrage_niveau",
      "b_siphon_debit",
      "b_siphon_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit",
      "b_barrage_debit"
    ),
    noms = c(
      "volet1",
      "volet2",
      "volet3",
      "volet4",
      "volet5",
      "vanne1",
      "vanne2",
      "vanne3",
      "vanne4",
      "vanne5",
      "debit_vilaine_estime",
      "debit_passe",
      "debit_moyen_cran",
      "tot_vol_barrage",
      "tot_vol_passe",
      "tot_vol_siphon",
      "tot_vol_volet",
      "tot_vol_ecluse",
      "niveauvilaine",
      "niveaumer",
      "niveauvilaineb",
      "niveaumerb",
      "debit_siphon_1",
      "debit_siphon_2",
      "debit_vanne1",
      "debit_vanne2",
      "debit_vanne3",
      "debit_vanne4",
      "debit_vanne5",
      "debit_volet1",
      "debit_volet2",
      "debit_volet3",
      "debit_volet4",
      "debit_volet5"
    ),
    tags = c(rep(as.integer(NA), 10),
             as.integer(
               c(
                 2515,
                 2523,
                 1900,
                 # pont de cran
                 2550:2554,
                 NA,
                 NA,
                 2507,
                 2508,
                 1528,
                 #siphon debit
                 1565,
                 #siphon debit 2
                 2571,
                 #debit vanne1
                 2572,
                 2573,
                 2574,
                 2575,
                 2581,
                 2582,
                 2583,
                 2584,
                 2585
                 
               )
             )),
    daterondes = c(rep("constant", 10), rep("linear", 24)),
    debut = as.POSIXct(strptime(debut, format = "%Y-%m-%d %H:%M:%S")),
    fin = as.POSIXct(strptime(fin, format = "%Y-%m-%d %H:%M:%S"))
  )
  # avec graphe = TRUE des png sont créés dans imgwd
  dat <- loaddb(bil, plot = plot)@bilandata
  return(dat)
}
