# WARNING - Generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand

#' Calcul du débit sur tous les volets
#' 
#' Somme du débit de tous les volets
#' 
#' @return
#' 
#' @export
debit_volets <-
  function(hvolet1,
           hvolet2,
           hvolet3,
           hvolet4,
           hvolet5,
           hvilaine,
           hvanne1,
           hvanne2,
           hvanne3,
           hvanne4,
           hvanne5,
           hmer,
           Cvo = 0.392) {
    Qv1 <- debit_volet(hvolet1, hvilaine, hvanne1, hmer, Cvo)
    Qv2 <- debit_volet(hvolet2, hvilaine, hvanne2, hmer, Cvo)
    Qv3 <- debit_volet(hvolet3, hvilaine, hvanne3, hmer, Cvo)
    Qv4 <- debit_volet(hvolet4, hvilaine, hvanne4, hmer, Cvo)
    Qv5 <- debit_volet(hvolet5, hvilaine, hvanne5, hmer, Cvo)
    return(
      data.frame(
        "Qvolet1" = Qv1,
        "Qvolet2" = Qv2,
        "Qvolet3" = Qv3,
        "Qvolet4" = Qv4,
        "Qvolet5" = Qv5
      )
    )
  }
