# WARNING - Generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand

#' Débit d'un volet
#' 
#' Formule déversoir à crête épaisse (Ferrette, 2004).
#' 
#' @param hvolet La hauteur du volet.
#' @param hvilaine Le niveau Vilaine.
#' @param hvanne La hauteur de vanne.
#' @param hmer Le niveau mer.
#' @param Cvo Le coefficient de débit sur le volet défaut 0.627.
#' @param g La pesanteur, toujours 9.81.
#' @param l La largeur d'une vanne 16.4
#'
#' @return Le calcul de débit d'un volet Q
#' @author Cedric Briand \email{cedric.briand@eaux-et-vilaine.bzh}, Stephanie Woimant 
#' \email{stephanie.woimant@eaux-et-vilaine.bzh} 
#' @export
#' @examples
#' load(system.file("param2012_2014.Rdata", package = "SIVA"))
#' load(system.file("dat2019.Rdata", package = "SIVA"))
#' dv <-debit_volet(
#'   hvolet = dat$volet1,
#'   hvilaine = dat$niveauvilaine,
#'   hvanne = dat$vanne1,
#'   hmer = dat$niveaumer,
#'   Cvo = param["Cvo"]
#' )
debit_volet = function(hvolet,
                       hvilaine,
                       hvanne,
                       hmer,
                       Cvo = 0.627,
                       g = 9.81,
                       l = 16.4) {
  H0 = ifelse(hvilaine >= 1.38 &
                hvolet < 3.5 & hvanne == 0 & hvilaine > hmer + 0.3,
              hvilaine - 1.38,
              0)
  Q = l * Cvo * (2 / 3 * g) ^ 0.5 * (H0) ^ 1.5
}
