# WARNING - Generated by {fusen} from /dev/flat_debit.Rmd: do not edit by hand

#' Traitement des données en sortie de SIVA
#' 
#' recalcule des données des compteurs, enlève les valeurs abérrantes des débits
#' des siphons
#' 
#' @param dat Un tableau de données cont
#' 
#' @return Un tableau de données propres
#' 
#' @export
#' @examples
#' # voir example-bilansiva-debit pour le chargement des données de 2020 dans SIVA
#' load(system.file("rawdata2020.Rdata", package="SIVA"))
#' plot(rawdata2020$tot_vol_barrage)
#' # les totaliseurs sont remis à plat
#' cordata2020 <- traitement_siva(dat=rawdata2020)
#' plot(cordata2020$tot_vol_barrage)
traitement_siva <- function(dat) {
  # avant 2016 les variables n'existent pas, pb de "tags"
  if (min(as.numeric(dat$horodate)) < 1451607000)	{
    dat <- dat[, -grep("Tag", colnames(dat))]
  }
  # colonnes contenant les cumuls
  totcol <- grep("tot", colnames(dat))
  volumes <- dat[, totcol]
  volumes[2:nrow(volumes), ] <-
    volumes[2:nrow(volumes), ] - volumes[1:(nrow(volumes) - 1), ]
  volumes <- volumes[-1, ]
  volumes[volumes < 0] <- NA
  dat[2:nrow(dat), totcol] <- volumes
  dat$tot_vol = rowSums(dat[, totcol])
    dat[dat$tot_vol_barrage > 1e5 &
        !is.na(dat$tot_vol_passe), "tot_vol_barrage"] <- NA
  dat[dat$tot_vol_passe > 1e5 &
        !is.na(dat$tot_vol_passe), "tot_vol_passe"] <- NA
  dat[dat$tot_vol_siphon > 1e5 &
        !is.na(dat$tot_vol_siphon), "tot_vol_siphon"] <- NA
  dat[dat$tot_vol_volet > 60000 &
        !is.na(dat$tot_vol_volet), "tot_vol_volet"] <- NA
  dat$tot_vol_siphon[(dat$tot_vol_siphon / 600) > 2 * 3.8 &
                       !is.na(dat$tot_vol_siphon)] <- NA
  dat$debit_siphon_1[dat$debit_siphon_1 > 3.8] <- NA
  dat$debit_siphon_2[dat$debit_siphon_2 > 3.8] <- NA
  return(dat)
  
}
